server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        provider:
          springOAuth2:
            authorization-uri: http://localhost:9000/oauth2/authorize
            issuer-uri: http://localhost:9000
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo

        registration:
          springOAuth2:
            authorization-grant-type: authorization_code
            client-id: giantStep-oauth2-client-app
            client-name: giantStep-oauth2-client-app
            client-secret: 1234
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/springoauth2
            scope: openid, read, write, photo, friend